name: "Plan Dev"

on:
  pull_request:
    paths:
      - "envs/dev/**"

jobs:
  plan:
    uses: alvaro-gcp-platform/terraform-ci-workflows/.github/workflows/terraform-plan.yml@main
    with:
      working_directory: "envs/dev"
      environment: "dev"
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_SA_KEY_DEV }}
