name: "Terraform CI"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Format and Validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format
        id: fmt
        # El format puede quedarse en la raíz porque usa -recursive
        run: terraform fmt -check -recursive 

      - name: Terraform Init
        id: init
        working-directory: ./envs/dev
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        working-directory: ./envs/dev
        run: terraform validate -no-color
